# Generated by Django 5.2.3 on 2025-09-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner_status',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='carted_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_when_added',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='expiry',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
