# Generated by Django 5.2.3 on 2025-09-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cart_owner_status_remove_cartitem_carted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cartitem',
        ),
    ]
