# Generated by Django 5.2.3 on 2025-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='techhub', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
