# Generated by Django 5.2.3 on 2025-09-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
