# Generated by Django 5.2.3 on 2025-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
