# Generated by Django 5.2.3 on 2025-09-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_brands_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
