# Generated by Django 5.2.3 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cartitem_current_price_cartitem_total_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=150000, max_digits=10),
        ),
    ]
