# Generated by Django 5.2.3 on 2025-09-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_products_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total_order',
        ),
    ]
