# Generated by Django 5.2.3 on 2025-09-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_order_total_order_total_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordereditem',
            table='ordereditem',
        ),
    ]
