# Generated by Django 5.2.3 on 2025-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_ordereditem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
