# Generated by Django 5.2.3 on 2025-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_owner_ordereditem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
