# Generated by Django 5.2.3 on 2025-09-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_paymentmethod_savedcard_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
