# Generated by Django 5.2.3 on 2025-09-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Expiry', models.DateTimeField()),
                ('user_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verif', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
