# Generated by Django 5.2.3 on 2025-09-25 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='Expiry',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user_status',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
