# Generated by Django 5.2.3 on 2025-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
