# Generated by Django 5.2.3 on 2025-10-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_main_imagge',
            new_name='is_main_image',
        ),
    ]
