# Generated by Django 5.2.3 on 2025-10-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_is_main_imagge_productimage_is_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
