# Generated by Django 5.2.3 on 2025-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product']},
        ),
        migrations.AddField(
            model_name='user',
            name='complete_status',
            field=models.CharField(default='10%', max_length=20),
        ),
    ]
