# Generated by Django 5.2.3 on 2025-10-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_cartitem_options_user_complete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_joined',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='complete_status',
        ),
    ]
